In [13]:
import pandas as pd
import numpy as np

house_numbers = [1002, 1003, 1004, 1005, 1010]

np_list = np.array(house_numbers)

series_data = pd.Series(house_numbers, index=["A1", "A2", "A3", "A4", "A5"])


series_data.info()

<class 'pandas.core.series.Series'>
Index: 5 entries, A1 to A5
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 80.0+ bytes

In [ ]:
utils = {
    "item":  ["pen", "book", "bag"],
    "price": [20, 150, 900],
    "stock": [100, 40, 12],
}

df = pd.DataFrame(utils, index=["A1", "A2", "A3"])

df.describe()

            price       stock
count    3.000000    3.000000
mean   356.666667   50.666667
std    475.008772   44.959241
min     20.000000   12.000000
25%     85.000000   26.000000
50%    150.000000   40.000000
75%    525.000000   70.000000
max    900.000000  100.000000

In [1]:
class Account:
    def __init__(self, owner):
        self.owner = owner
        self.balance = 0

class Savings(Account):
    def __init__(self, owner):
        self.rate = 5

s = Savings("Ali")
print(s.balance)

AttributeError: 'Savings' object has no attribute 'balance'

In [2]:
import numpy as np

a = np.array([80, 72])
a[0] = 85.7
print(a[0])

85

In [3]:
marks = ["91", "100", "82"]   # read from a CSV file
print(max(marks))

91

In [5]:
house_numbers = [1004, 1005, 1006, 1008]
print(pd.Series(house_numbers, index=["A1", "A2", "A3", "A4"]))

A1    1004
A2    1005
A3    1006
A4    1008
dtype: int64

In [7]:
utils = {
    "item":  ["pen", "book", "bag"],
    "price": [20, 150, 900],
    "stock": [100, 40, 12],
}

df = pd.DataFrame(utils)

df.head()

   item  price  stock
0   pen     20    100
1  book    150     40
2   bag    900     12

In [10]:
# df.describe()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   item    3 non-null      object
 1   price   3 non-null      int64
 2   stock   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes